### ISSUE TITLE
loki-promtail-daemonset.yaml contains a predefined node affinity section that prevents the daemonsets from deploying. 

### ISSUE THREAD

**Issue by aintbrokedontfix** [sassoftware/iot-kubernetes-monitoring-esp#8]
the `loki-promtail-daemonset.yaml` contains a predefined node `affinity` section that prevents the daemonsets from deploying causing Loki based dashboards to fail (no data shown). The `tolerations` section also seems unnecessary.

The following section should be removed or perhaps guidance provided on how to make sure promtail runs only on ESP nodes?
```yaml
      tolerations:
      - operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: agentpool
                    operator: In
                    values:
                      - compute
```

To have promtail to run on ESP nodes labeled with `workload.sas.com/class=esp` the manifest should be updated to this:

```yaml
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload.sas.com/class
                    operator: In
                    values:
                      - esp
```
